### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by jpcaveiro** [alanvalejo/rgcli#1]
Is possible to make available the referenced software?

The following link is broken:

    You can download the RGCLI software in http://www.alanvalejo.com.br/software?name=rgcli

**Comment by lberton** [comment]
I think I didn't save the code :/
Could you write to Alan and ask if he can check/ fix the link in his github?

***@***.***

***@***.***




Em ter, 27 de jul de 2021 01:09, João Pedro ***@***.***>
escreveu:
